2024-08-04 16:01:22,588:ERROR:An error occurred: HTTPSConnectionPool(host='www.spiderbuf.cn', port=443): Max retries exceeded with url: /playground/iplist (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002C68D0D6700>: Failed to resolve '1270.0.0.1' ([Errno 11001] getaddrinfo failed)")))
2024-08-04 16:01:53,214:ERROR:An error occurred: HTTPSConnectionPool(host='www.spiderbuf.cn', port=443): Max retries exceeded with url: /playground/iplist (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027FA4457580>: Failed to resolve '1270.0.0.1' ([Errno 11001] getaddrinfo failed)")))
2024-08-04 16:01:56,548:ERROR:An error occurred: HTTPSConnectionPool(host='www.spiderbuf.cn', port=443): Max retries exceeded with url: /playground/iplist (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001BBD50D0850>: Failed to resolve '1270.0.0.1' ([Errno 11001] getaddrinfo failed)")))
2024-08-04 16:01:59,298:ERROR:An error occurred: HTTPSConnectionPool(host='www.spiderbuf.cn', port=443): Max retries exceeded with url: /playground/iplist (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000021DE6556670>: Failed to resolve '1270.0.0.1' ([Errno 11001] getaddrinfo failed)")))
2024-08-04 16:02:18,726:ERROR:An error occurred: HTTPSConnectionPool(host='www.spiderbuf.cn', port=443): Max retries exceeded with url: /playground/iplist (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001967CED0A60>: Failed to resolve '1270.0.0.1' ([Errno 11001] getaddrinfo failed)")))
2024-08-04 16:03:05,420:ERROR:An error occurred: HTTPSConnectionPool(host='www.spiderbuf.cn', port=443): Max retries exceeded with url: /playground/iplist (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001A31B157490>: Failed to resolve '1270.0.0.1' ([Errno 11001] getaddrinfo failed)")))
2024-08-04 16:03:51,236:INFO:Successfully accessed the website: 200
2024-08-04 18:26:44,020:INFO:Successfully accessed the website: 200
2024-08-04 18:28:03,971:INFO:Successfully accessed the website: 200
2024-08-04 18:30:23,047:INFO:Successfully accessed the website: 200
2024-08-04 20:40:19,382:INFO:Successfully accessed the website: 200
